### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by jorzuniga** [builtbybel/sharpapp#31]
I how can i reinstall OneDrive, just need this app

**Comment by frenchr** [comment]
Fortunately, it is easy to reinstall OneDrive.
Just go to this location : https://go.microsoft.com/fwlink/p/?LinkID=2121808&clcid=0x409&culture=en-us&country=US
Then run the downloaded file. It will reinstall OneDrive on your machine.

**Comment by jorzuniga** [comment]
its not work because this generated a trouble
HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive" "DisableFileSyncNGSC" 1
And when i made a change on this (change to 0 value) and reboot the pc the value say 1 again!

**Comment by Belim** [comment]
I would simply reinstall the app like you have already done.  So that's that.
